services:

  php:
    build: ../
    image: php:fpm
    container_name: rpgmanager_php-fpm
    tty: true
    volumes:
      - ../:/var/www/rpgmanager/
      - ../php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: rpgmanager_web
    restart: always
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../:/var/www/rpgmanager/
      - ./config/nginx.conf:/etc/nginx/conf.d/rpgmanager.conf
    links:
      - php
    networks:
      - app-network  

  mysql:
    image: mysql
    container_name: rpgmanager_db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=rpgmanager'
      - 'MYSQL_ROOT_PASSWORD=root'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
volumes:
  dbdata:
    driver: local